---
application:
  name: "peerjs-server"
  project: "peerjs"
  organization: "QoveryCommunity"
routers:
- name: "main-peerjs-server"
custom_domains:
  - branch: master
    domain: peer.hll.nu
  routes:
  - application_name: "peerjs-server"
    paths:
    - "/*"
